"""
Sahm Backend — Model Registry
All models imported here for Alembic auto-detection.
"""
from app.models.base import Base
from app.models.user import User, UserRole
from app.models.college import College, Specialization
from app.models.batch import Batch, BatchStatus, CertificateType
from app.models.record import StudentRecord, CertificateStatus
from app.models.source_image import SourceImage
from app.models.audit_log import AuditLog
from app.models.export_studio import (
    ExportFormat,
    TemplateCategory,
    JobStatus,
    ExportTemplate,
    TemplateVersion,
    ExportProfile,
    ExportJob,
    GeneratedArtifact,
    DocumentVerification,
)
from app.models.batch_scanner import (
    BatchSessionStatus,
    ItemProcessingState,
    ProcessingMode,
    BatchPriority,
    QualityCategory,
    MatchStatus,
    DuplicateStatus,
    CandidateResolutionStatus,
    BatchScanSession,
    BatchScanItem,
    BatchScanSegment,
    MissingStudentCandidate,
    BatchScanReview,
)
from app.models.verification import (
    VerificationState,
    PublicVerificationResult,
    PrivacyProfile,
    DisplayNameMode,
    RevocationReason,
    PublicationStatus,
    CertificateVerification,
    VerificationPublicView,
    PublicVerificationPolicy,
    VerificationEvent,
    VerificationAccessLog,
)
from app.models.ai_governance import (
    ModelCapability,
    ModelStatus,
    PrivacyClassification,
    CostClass,
    DatasetClassification,
    FeedbackType,
    ErrorCategory,
    IncidentSeverity,
    IncidentStatus,
    ReprocessingStatus,
    AIProviderConfig,
    AIModel,
    AIRun,
    EvaluationDataset,
    EvaluationSample,
    EvaluationRun,
    AIGovernancePolicy,
    HumanFeedback,
    DriftAlert,
    AIIncident,
    ReprocessingCampaign,
)
from app.models.handoff import (
    HandoffType,
    HandoffStatus,
    TransferMethod,
    ShareRole,
    ConflictClass,
    MergeStrategy,
    DataClassification,
    DeviceTrustStatus,
    DLPPolicyAction,
    WorkHandoff,
    HandoffSnapshot,
    HandoffPackage,
    HandoffChunk,
    HandoffAuditLog,
    SharedWorkspace,
    SharedWorkspaceMember,
    ItemClaim,
    DeviceRegistration,
    DataLossPreventionPolicy,
)

__all__ = [
    "Base",
    "User",
    "UserRole",
    "College",
    "Specialization",
    "Batch",
    "BatchStatus",
    "CertificateType",
    "StudentRecord",
    "CertificateStatus",
    "SourceImage",
    "AuditLog",
    "ExportFormat",
    "TemplateCategory",
    "JobStatus",
    "ExportTemplate",
    "TemplateVersion",
    "ExportProfile",
    "ExportJob",
    "GeneratedArtifact",
    "DocumentVerification",
    "BatchSessionStatus",
    "ItemProcessingState",
    "ProcessingMode",
    "BatchPriority",
    "QualityCategory",
    "MatchStatus",
    "DuplicateStatus",
    "CandidateResolutionStatus",
    "BatchScanSession",
    "BatchScanItem",
    "BatchScanSegment",
    "MissingStudentCandidate",
    "BatchScanReview",
    "VerificationState",
    "PublicVerificationResult",
    "PrivacyProfile",
    "DisplayNameMode",
    "RevocationReason",
    "PublicationStatus",
    "CertificateVerification",
    "VerificationPublicView",
    "PublicVerificationPolicy",
    "VerificationEvent",
    "VerificationAccessLog",
    "ModelCapability",
    "ModelStatus",
    "PrivacyClassification",
    "CostClass",
    "DatasetClassification",
    "FeedbackType",
    "ErrorCategory",
    "IncidentSeverity",
    "IncidentStatus",
    "ReprocessingStatus",
    "AIProviderConfig",
    "AIModel",
    "AIRun",
    "EvaluationDataset",
    "EvaluationSample",
    "EvaluationRun",
    "AIGovernancePolicy",
    "HumanFeedback",
    "DriftAlert",
    "AIIncident",
    "ReprocessingCampaign",
    "HandoffType",
    "HandoffStatus",
    "TransferMethod",
    "ShareRole",
    "ConflictClass",
    "MergeStrategy",
    "DataClassification",
    "DeviceTrustStatus",
    "DLPPolicyAction",
    "WorkHandoff",
    "HandoffSnapshot",
    "HandoffPackage",
    "HandoffChunk",
    "HandoffAuditLog",
    "SharedWorkspace",
    "SharedWorkspaceMember",
    "ItemClaim",
    "DeviceRegistration",
    "DataLossPreventionPolicy",
]



